CREATE TABLE "orders" (
	"id" serial PRIMARY KEY NOT NULL,
	"type" varchar(20) DEFAULT 'FOOD' NOT NULL,
	"code" varchar(50) NOT NULL,
	"status" varchar(20) DEFAULT 'PENDING' NOT NULL,
	"is_holiday" boolean DEFAULT false NOT NULL,
	"is_rain" boolean DEFAULT false NOT NULL,
	"distance" numeric(15, 2) DEFAULT '0.00' NOT NULL,
	"total_delivery" numeric(15, 2) DEFAULT '0.00' NOT NULL,
	"total_product" numeric(15, 2) DEFAULT '0.00' NOT NULL,
	"total_voucher" numeric(15, 2) DEFAULT '0.00' NOT NULL,
	"user_service_fee" numeric(15, 2) DEFAULT '0.00' NOT NULL,
	"store_service_fee" numeric(15, 2) DEFAULT '0.00' NOT NULL,
	"total" numeric(15, 2) DEFAULT '0.00' NOT NULL,
	"income_delivery" numeric(15, 2) DEFAULT '0.00' NOT NULL,
	"pay_for_shop" numeric(15, 2) DEFAULT '0.00' NOT NULL,
	"is_rated" boolean DEFAULT false NOT NULL,
	"address_from" varchar(255) NOT NULL,
	"geometry_from" varchar(255) NOT NULL,
	"address_to" varchar(255) NOT NULL,
	"geometry_to" varchar(255) NOT NULL,
	"name_for_contact" varchar(255),
	"phone_for_contact" varchar(20),
	"note" text,
	"user_id" integer NOT NULL,
	"deliver_id" integer,
	"store_id" integer,
	"area_id" integer,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
