CREATE TABLE "delivers" (
	"id" serial PRIMARY KEY NOT NULL,
	"role" varchar DEFAULT 'DELIVER' NOT NULL,
	"id_card" varchar NOT NULL,
	"phone" varchar NOT NULL,
	"email" varchar NOT NULL,
	"full_name" varchar NOT NULL,
	"avatar" varchar,
	"password" varchar NOT NULL,
	"gender" varchar(255),
	"date_of_birth" date,
	"cancel_order_count" integer DEFAULT 0,
	"rating" numeric(10, 2),
	"point" numeric(10, 2) DEFAULT 0,
	"status" boolean DEFAULT true,
	"activated" boolean DEFAULT false,
	"fcm_token" varchar,
	"refresh_token" varchar,
	"area_id" integer,
	"deleted_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
